/**
 * Curated built-in games — always available in the arcade.
 * These are hand-crafted Phaser 3 games that ship with PixelForge.
 * They demonstrate the platform quality and fill the arcade on day 1.
 */
import type { Game } from './types'

export const CURATED_GAMES: Game[] = [
  {
    id: 'builtin-math-rush',
    title: 'Math Rush',
    description: 'Beat the clock — solve maths problems across 5 difficulty levels. Streak bonuses. Get every answer right!',
    prompt: 'educational maths quiz game with timer and streak system',
    htmlUrl: '/games/math-rush.html',
    thumbnailUrl: '',
    genre: 'educational',
    ageRating: '8+',
    status: 'published',
    authorId: 'pixelforge',
    authorName: 'PixelForge',
    playCount: 0,
    likeCount: 0,
    remixCount: 0,
    createdAt: '2026-05-10T00:00:00Z',
    publishedAt: '2026-05-10T00:00:00Z',
    controls: ['Click answer buttons or press 1–4', 'Gamepad A/B/X/Y — choose answer', 'Tap on mobile', 'R — restart after game over'],
  },
  {
    id: 'builtin-vocab-blaster',
    title: 'Vocab Blaster',
    description: 'Words fall from the sky — click the correct English translation before they hit the ground. Spanish, French, Japanese, German.',
    prompt: 'language learning vocabulary falling words game',
    htmlUrl: '/games/vocab-blaster.html',
    thumbnailUrl: '',
    genre: 'educational',
    ageRating: '8+',
    status: 'published',
    authorId: 'pixelforge',
    authorName: 'PixelForge',
    playCount: 0,
    likeCount: 0,
    remixCount: 0,
    createdAt: '2026-05-10T00:00:00Z',
    publishedAt: '2026-05-10T00:00:00Z',
    controls: ['Click / tap the correct English translation', 'Words fall faster each level', 'R — restart after game over'],
  },
  {
    id: 'builtin-space-battle',
    title: 'Stellar Assault',
    description: 'Epic space battle — dodge enemy fire, unleash power-ups, defeat bosses. Endless action!',
    prompt: 'space battle shoot em up with bosses and power-ups',
    htmlUrl: '/games/space-battle.html',
    thumbnailUrl: '',
    genre: 'shooter',
    ageRating: '8+',
    status: 'published',
    authorId: 'pixelforge',
    authorName: 'PixelForge',
    playCount: 0,
    likeCount: 0,
    remixCount: 0,
    createdAt: '2026-05-10T00:00:00Z',
    publishedAt: '2026-05-10T00:00:00Z',
    controls: ['← → / A D — move ship', 'Z / Space / auto-fire enabled', 'Tap left/right/center on mobile', 'R — restart after game over'],
  },
  {
    id: 'builtin-racing',
    title: 'Turbo Drift',
    description: 'Top-down racer — drift through corners, avoid traffic, beat your high score.',
    prompt: 'top-down racing game with drifting',
    htmlUrl: '/games/racing.html',
    thumbnailUrl: '',
    genre: 'arcade',
    ageRating: '8+',
    status: 'published',
    authorId: 'pixelforge',
    authorName: 'PixelForge',
    playCount: 0,
    likeCount: 0,
    remixCount: 0,
    createdAt: '2026-05-07T00:00:00Z',
    publishedAt: '2026-05-07T00:00:00Z',
    controls: ['← → / A D — change lane', 'Tap left/right half of screen on mobile', 'R — restart after crash'],
  },
  {
    id: 'builtin-shooter',
    title: 'Galactic Assault',
    description: 'Vertical shoot-em-up. Survive waves, collect power-ups, destroy the mothership.',
    prompt: 'vertical scrolling shoot em up',
    htmlUrl: '/games/shooter.html',
    thumbnailUrl: '',
    genre: 'shooter',
    ageRating: '8+',
    status: 'published',
    authorId: 'pixelforge',
    authorName: 'PixelForge',
    playCount: 0,
    likeCount: 0,
    remixCount: 0,
    createdAt: '2026-05-07T00:00:00Z',
    publishedAt: '2026-05-07T00:00:00Z',
    controls: ['Arrow keys — move ship', 'Space — fire (hold for auto-fire)', 'R — restart'],
  },
  {
    id: 'builtin-snake',
    title: 'Neon Snake',
    description: 'Classic snake with neon visuals, speed boosts and wall-wrap. How long can you grow?',
    prompt: 'neon snake game with speed boosts',
    htmlUrl: '/games/snake.html',
    thumbnailUrl: '',
    genre: 'arcade',
    ageRating: '8+',
    status: 'published',
    authorId: 'pixelforge',
    authorName: 'PixelForge',
    playCount: 0,
    likeCount: 0,
    remixCount: 0,
    createdAt: '2026-05-07T00:00:00Z',
    publishedAt: '2026-05-07T00:00:00Z',
    controls: ['Arrow keys / WASD — steer snake', 'Collect pink orbs for bonus points', 'R — restart'],
  },
  {
    id: 'builtin-asteroids',
    title: 'Asteroid Storm',
    description: 'Dodge and blast asteroids in deep space. Bosses appear every 3 waves.',
    prompt: 'asteroids space shooter',
    htmlUrl: '/games/asteroids.html',
    thumbnailUrl: '',
    genre: 'shooter',
    ageRating: '8+',
    status: 'published',
    authorId: 'pixelforge',
    authorName: 'PixelForge',
    playCount: 0,
    likeCount: 0,
    remixCount: 0,
    createdAt: '2026-05-07T00:00:00Z',
    publishedAt: '2026-05-07T00:00:00Z',
    controls: ['← → — rotate ship', '↑ — thrust forward', 'Space — fire', 'R — restart'],
  },
  {
    id: 'builtin-jumper',
    title: 'Pixel Jumper',
    description: 'Infinite platformer. Jump across platforms, collect gems, avoid spikes.',
    prompt: 'infinite platformer with gems',
    htmlUrl: '/games/jumper.html',
    thumbnailUrl: '',
    genre: 'platformer',
    ageRating: '8+',
    status: 'published',
    authorId: 'pixelforge',
    authorName: 'PixelForge',
    playCount: 0,
    likeCount: 0,
    remixCount: 0,
    createdAt: '2026-05-07T00:00:00Z',
    publishedAt: '2026-05-07T00:00:00Z',
    controls: ['← → / A D — run left/right', '↑ / Space / W — jump (press again for double jump)', 'R — restart'],
  },
  {
    id: 'builtin-breakout',
    title: 'Block Blitz',
    description: 'Breakout with power-ups, multi-ball madness and 10 escalating levels.',
    prompt: 'breakout brick breaker with power-ups',
    htmlUrl: '/games/breakout.html',
    thumbnailUrl: '',
    genre: 'arcade',
    ageRating: '8+',
    status: 'published',
    authorId: 'pixelforge',
    authorName: 'PixelForge',
    playCount: 0,
    likeCount: 0,
    remixCount: 0,
    createdAt: '2026-05-07T00:00:00Z',
    publishedAt: '2026-05-07T00:00:00Z',
    controls: ['← → / A D — move paddle', 'Mouse — move paddle (click to launch)', 'R — restart'],
  },
  {
    id: 'builtin-typing-racer',
    title: 'Typing Racer',
    description: 'Race against the clock by typing words correctly. Speed up your WPM across 5 difficulty levels!',
    prompt: 'typing speed game with cars and WPM tracking',
    htmlUrl: '/games/typing-racer.html',
    thumbnailUrl: '',
    genre: 'educational',
    ageRating: '8+',
    status: 'published',
    authorId: 'pixelforge',
    authorName: 'PixelForge',
    playCount: 0,
    likeCount: 0,
    remixCount: 0,
    createdAt: '2026-05-11T00:00:00Z',
    publishedAt: '2026-05-11T00:00:00Z',
    controls: ['Type the highlighted word', 'Press Space to confirm word', 'Race gets faster each level', 'R — restart after game over'],
  },
  {
    id: 'builtin-tower-defense',
    title: 'Tower Defense',
    description: 'Place towers to stop waves of enemies. Earn gold, upgrade towers, survive 10 waves!',
    prompt: 'tower defense strategy game with waves and upgrades',
    htmlUrl: '/games/tower-defense.html',
    thumbnailUrl: '',
    genre: 'puzzle',
    ageRating: '8+',
    status: 'published',
    authorId: 'pixelforge',
    authorName: 'PixelForge',
    playCount: 0,
    likeCount: 0,
    remixCount: 0,
    createdAt: '2026-05-11T00:00:00Z',
    publishedAt: '2026-05-11T00:00:00Z',
    controls: ['Click grid to place tower', 'Click tower to upgrade/sell', 'Start Wave button to begin', 'R — restart after defeat'],
  },
  {
    id: 'builtin-card-battle',
    title: 'Card Battle',
    description: 'Strategic card game — play attack, defense, heal and crit cards to defeat AI enemies. New opponent each round!',
    prompt: 'turn-based card battle game with AI opponent',
    htmlUrl: '/games/card-battle.html',
    thumbnailUrl: '',
    genre: 'rpg',
    ageRating: '8+',
    status: 'published',
    authorId: 'pixelforge',
    authorName: 'PixelForge',
    playCount: 0,
    likeCount: 0,
    remixCount: 0,
    createdAt: '2026-05-11T00:00:00Z',
    publishedAt: '2026-05-11T00:00:00Z',
    controls: ['Click a card to play it', '1–4 keyboard shortcuts for cards', 'R — restart after battle'],
  },
]
