/**
 * Curated built-in games — always available in the arcade.
 * These are hand-crafted Phaser 3 games that ship with PixelForge.
 * They demonstrate the platform quality and fill the arcade on day 1.
 */
import type { Game } from './types'

export const CURATED_GAMES: Game[] = [
  {
    id: 'builtin-racing',
    title: 'Turbo Drift',
    description: 'Top-down racer — drift through corners, avoid traffic, beat your high score.',
    prompt: 'top-down racing game with drifting',
    htmlUrl: '/games/racing.html',
    thumbnailUrl: '',
    genre: 'arcade',
    ageRating: '8+',
    status: 'published',
    authorId: 'pixelforge',
    authorName: 'PixelForge',
    playCount: 0,
    likeCount: 0,
    remixCount: 0,
    createdAt: '2026-05-07T00:00:00Z',
    publishedAt: '2026-05-07T00:00:00Z',
  },
  {
    id: 'builtin-shooter',
    title: 'Galactic Assault',
    description: 'Vertical shoot-em-up. Survive waves, collect power-ups, destroy the mothership.',
    prompt: 'vertical scrolling shoot em up',
    htmlUrl: '/games/shooter.html',
    thumbnailUrl: '',
    genre: 'shooter',
    ageRating: '8+',
    status: 'published',
    authorId: 'pixelforge',
    authorName: 'PixelForge',
    playCount: 0,
    likeCount: 0,
    remixCount: 0,
    createdAt: '2026-05-07T00:00:00Z',
    publishedAt: '2026-05-07T00:00:00Z',
  },
  {
    id: 'builtin-snake',
    title: 'Neon Snake',
    description: 'Classic snake with neon visuals, speed boosts and wall-wrap. How long can you grow?',
    prompt: 'neon snake game with speed boosts',
    htmlUrl: '/games/snake.html',
    thumbnailUrl: '',
    genre: 'arcade',
    ageRating: '8+',
    status: 'published',
    authorId: 'pixelforge',
    authorName: 'PixelForge',
    playCount: 0,
    likeCount: 0,
    remixCount: 0,
    createdAt: '2026-05-07T00:00:00Z',
    publishedAt: '2026-05-07T00:00:00Z',
  },
  {
    id: 'builtin-asteroids',
    title: 'Asteroid Storm',
    description: 'Dodge and blast asteroids in deep space. Bosses appear every 3 waves.',
    prompt: 'asteroids space shooter',
    htmlUrl: '/games/asteroids.html',
    thumbnailUrl: '',
    genre: 'shooter',
    ageRating: '8+',
    status: 'published',
    authorId: 'pixelforge',
    authorName: 'PixelForge',
    playCount: 0,
    likeCount: 0,
    remixCount: 0,
    createdAt: '2026-05-07T00:00:00Z',
    publishedAt: '2026-05-07T00:00:00Z',
  },
  {
    id: 'builtin-jumper',
    title: 'Pixel Jumper',
    description: 'Infinite platformer. Jump across platforms, collect gems, avoid spikes.',
    prompt: 'infinite platformer with gems',
    htmlUrl: '/games/jumper.html',
    thumbnailUrl: '',
    genre: 'platformer',
    ageRating: '8+',
    status: 'published',
    authorId: 'pixelforge',
    authorName: 'PixelForge',
    playCount: 0,
    likeCount: 0,
    remixCount: 0,
    createdAt: '2026-05-07T00:00:00Z',
    publishedAt: '2026-05-07T00:00:00Z',
  },
  {
    id: 'builtin-breakout',
    title: 'Block Blitz',
    description: 'Breakout with power-ups, multi-ball madness and 10 escalating levels.',
    prompt: 'breakout brick breaker with power-ups',
    htmlUrl: '/games/breakout.html',
    thumbnailUrl: '',
    genre: 'arcade',
    ageRating: '8+',
    status: 'published',
    authorId: 'pixelforge',
    authorName: 'PixelForge',
    playCount: 0,
    likeCount: 0,
    remixCount: 0,
    createdAt: '2026-05-07T00:00:00Z',
    publishedAt: '2026-05-07T00:00:00Z',
  },
]
