/**
 * Curated built-in games — always available in the arcade.
 * These are hand-crafted Phaser 3 games that ship with PixelForge.
 * They demonstrate the platform quality and fill the arcade on day 1.
 */
import type { Game } from './types'

export const CURATED_GAMES: Game[] = [
  {
    id: 'builtin-math-rush',
    title: 'Math Rush',
    description: 'Beat the clock — solve maths problems across 5 difficulty levels. Streak bonuses. Get every answer right!',
    prompt: 'educational maths quiz game with timer and streak system',
    htmlUrl: '/games/math-rush.html',
    thumbnailUrl: '/game-thumbs/builtin-math-rush.svg',
    genre: 'educational',
    ageRating: '8+',
    status: 'published',
    authorId: 'pixelforge',
    authorName: 'PixelForge',
    playCount: 0,
    likeCount: 0,
    remixCount: 0,
    createdAt: '2026-05-10T00:00:00Z',
    publishedAt: '2026-05-10T00:00:00Z',
    controls: ['Click answer buttons or press 1–4', 'Gamepad A/B/X/Y — choose answer', 'Tap on mobile', 'R — restart after game over'],
  },
  {
    id: 'builtin-vocab-blaster',
    title: 'Vocab Blaster',
    description: 'Words fall from the sky — click the correct English translation before they hit the ground. Spanish, French, Japanese, German.',
    prompt: 'language learning vocabulary falling words game',
    htmlUrl: '/games/vocab-blaster.html',
    thumbnailUrl: '/game-thumbs/builtin-vocab-blaster.svg',
    genre: 'educational',
    ageRating: '8+',
    status: 'published',
    authorId: 'pixelforge',
    authorName: 'PixelForge',
    playCount: 0,
    likeCount: 0,
    remixCount: 0,
    createdAt: '2026-05-10T00:00:00Z',
    publishedAt: '2026-05-10T00:00:00Z',
    controls: ['Click / tap the correct English translation', 'Words fall faster each level', 'R — restart after game over'],
  },
  {
    id: 'builtin-space-battle',
    title: 'Stellar Assault',
    description: 'Epic space battle — dodge enemy fire, unleash power-ups, defeat bosses. Endless action!',
    prompt: 'space battle shoot em up with bosses and power-ups',
    htmlUrl: '/games/space-battle.html',
    thumbnailUrl: '/game-thumbs/builtin-space-battle.svg',
    genre: 'shooter',
    ageRating: '8+',
    status: 'published',
    authorId: 'pixelforge',
    authorName: 'PixelForge',
    playCount: 0,
    likeCount: 0,
    remixCount: 0,
    createdAt: '2026-05-10T00:00:00Z',
    publishedAt: '2026-05-10T00:00:00Z',
    controls: ['← → / A D — move ship', 'Z / Space / auto-fire enabled', 'Tap left/right/center on mobile', 'R — restart after game over'],
  },
  {
    id: 'builtin-snake',
    title: 'Neon Snake',
    description: 'Classic snake with neon visuals, speed boosts and wall-wrap. How long can you grow?',
    prompt: 'neon snake game with speed boosts',
    htmlUrl: '/games/snake.html',
    thumbnailUrl: '/game-thumbs/builtin-snake.svg',
    genre: 'arcade',
    ageRating: '8+',
    status: 'published',
    authorId: 'pixelforge',
    authorName: 'PixelForge',
    playCount: 0,
    likeCount: 0,
    remixCount: 0,
    createdAt: '2026-05-07T00:00:00Z',
    publishedAt: '2026-05-07T00:00:00Z',
    controls: ['Arrow keys / WASD — steer snake', 'Collect pink orbs for bonus points', 'R — restart'],
  },
  {
    id: 'builtin-asteroids',
    title: 'Asteroid Storm',
    description: 'Dodge and blast asteroids in deep space. Bosses appear every 3 waves.',
    prompt: 'asteroids space shooter',
    htmlUrl: '/games/asteroids.html',
    thumbnailUrl: '/game-thumbs/builtin-asteroids.svg',
    genre: 'shooter',
    ageRating: '8+',
    status: 'published',
    authorId: 'pixelforge',
    authorName: 'PixelForge',
    playCount: 0,
    likeCount: 0,
    remixCount: 0,
    createdAt: '2026-05-07T00:00:00Z',
    publishedAt: '2026-05-07T00:00:00Z',
    controls: ['← → — rotate ship', '↑ — thrust forward', 'Space — fire', 'R — restart'],
  },
  {
    id: 'builtin-jumper',
    title: 'Pixel Jumper',
    description: 'Infinite platformer. Jump across platforms, collect gems, avoid spikes.',
    prompt: 'infinite platformer with gems',
    htmlUrl: '/games/jumper.html',
    thumbnailUrl: '/game-thumbs/builtin-jumper.svg',
    genre: 'platformer',
    ageRating: '8+',
    status: 'published',
    authorId: 'pixelforge',
    authorName: 'PixelForge',
    playCount: 0,
    likeCount: 0,
    remixCount: 0,
    createdAt: '2026-05-07T00:00:00Z',
    publishedAt: '2026-05-07T00:00:00Z',
    controls: ['← → / A D — run left/right', '↑ / Space / W — jump (press again for double jump)', 'R — restart'],
  },
  {
    id: 'builtin-breakout',
    title: 'Block Blitz',
    description: 'Breakout with power-ups, multi-ball madness and 10 escalating levels.',
    prompt: 'breakout brick breaker with power-ups',
    htmlUrl: '/games/breakout.html',
    thumbnailUrl: '/game-thumbs/builtin-breakout.svg',
    genre: 'arcade',
    ageRating: '8+',
    status: 'published',
    authorId: 'pixelforge',
    authorName: 'PixelForge',
    playCount: 0,
    likeCount: 0,
    remixCount: 0,
    createdAt: '2026-05-07T00:00:00Z',
    publishedAt: '2026-05-07T00:00:00Z',
    controls: ['← → / A D — move paddle', 'Mouse — move paddle (click to launch)', 'R — restart'],
  },
  {
    id: 'builtin-typing-racer',
    title: 'Typing Racer',
    description: 'Race against the clock by typing words correctly. Speed up your WPM across 5 difficulty levels!',
    prompt: 'typing speed game with cars and WPM tracking',
    htmlUrl: '/games/typing-racer.html',
    thumbnailUrl: '/game-thumbs/builtin-typing-racer.svg',
    genre: 'educational',
    ageRating: '8+',
    status: 'published',
    authorId: 'pixelforge',
    authorName: 'PixelForge',
    playCount: 0,
    likeCount: 0,
    remixCount: 0,
    createdAt: '2026-05-11T00:00:00Z',
    publishedAt: '2026-05-11T00:00:00Z',
    controls: ['Type the highlighted word', 'Press Space to confirm word', 'Race gets faster each level', 'R — restart after game over'],
  },
  {
    id: 'builtin-tower-defense',
    title: 'Tower Defense',
    description: 'Place towers to stop waves of enemies. Earn gold, upgrade towers, survive 10 waves!',
    prompt: 'tower defense strategy game with waves and upgrades',
    htmlUrl: '/games/tower-defense.html',
    thumbnailUrl: '/game-thumbs/builtin-tower-defense.svg',
    genre: 'puzzle',
    ageRating: '8+',
    status: 'published',
    authorId: 'pixelforge',
    authorName: 'PixelForge',
    playCount: 0,
    likeCount: 0,
    remixCount: 0,
    createdAt: '2026-05-11T00:00:00Z',
    publishedAt: '2026-05-11T00:00:00Z',
    controls: ['Click grid to place tower', 'Click tower to upgrade/sell', 'Start Wave button to begin', 'R — restart after defeat'],
  },
  {
    id: 'builtin-card-battle',
    title: 'Card Battle',
    description: 'Strategic card game — play attack, defense, heal and crit cards to defeat AI enemies. New opponent each round!',
    prompt: 'turn-based card battle game with AI opponent',
    htmlUrl: '/games/card-battle.html',
    thumbnailUrl: '/game-thumbs/builtin-card-battle.svg',
    genre: 'rpg',
    ageRating: '8+',
    status: 'published',
    authorId: 'pixelforge',
    authorName: 'PixelForge',
    playCount: 0,
    likeCount: 0,
    remixCount: 0,
    createdAt: '2026-05-11T00:00:00Z',
    publishedAt: '2026-05-11T00:00:00Z',
    controls: ['Click a card to play it', '1–4 keyboard shortcuts for cards', 'R — restart after battle'],
  },
  {
    id: 'builtin-runner',
    title: 'Endless Runner',
    description: 'Neon cyber runner — jump over obstacles, collect coins, survive as long as you can. Speed increases!',
    prompt: 'endless side-scrolling runner with obstacles and coins',
    htmlUrl: '/games/endless-runner.html',
    thumbnailUrl: '/game-thumbs/builtin-runner.svg',
    genre: 'arcade',
    ageRating: '8+',
    status: 'published',
    authorId: 'pixelforge',
    authorName: 'PixelForge',
    playCount: 0,likeCount: 0,remixCount: 0,
    createdAt: '2026-05-16T00:00:00Z',publishedAt: '2026-05-16T00:00:00Z',
    controls: ['Space / ↑ / Tap — jump', 'Collect gold coins (+50)', 'Speed increases over time'],
  },
  {
    id: 'builtin-tetris',
    title: 'Tetris',
    description: 'Stack falling tetrominoes, clear lines, survive the speed. Ghost piece, hard drop, dynamic level scaling.',
    prompt: 'tetris with ghost piece hard drop and level scaling',
    htmlUrl: '/games/tetris.html',
    thumbnailUrl: '/game-thumbs/builtin-tetris.svg',
    genre: 'puzzle',
    ageRating: '8+',
    status: 'published',
    authorId: 'pixelforge',
    authorName: 'PixelForge',
    playCount: 0, likeCount: 0, remixCount: 0,
    createdAt: '2026-05-16T00:00:00Z', publishedAt: '2026-05-16T00:00:00Z',
    controls: ['← → — move', '↑ — rotate', '↓ — soft drop', 'Space — hard drop', 'R — restart'],
  },
  {
    id: 'builtin-wordle',
    title: 'Wordle',
    description: 'Guess the 5-letter word in 6 tries. Green = correct spot, yellow = wrong spot. New word every game.',
    prompt: 'wordle word guessing game with color feedback',
    htmlUrl: '/games/wordle.html',
    thumbnailUrl: '/game-thumbs/builtin-wordle.svg',
    genre: 'puzzle',
    ageRating: '8+',
    status: 'published',
    authorId: 'pixelforge',
    authorName: 'PixelForge',
    playCount: 0, likeCount: 0, remixCount: 0,
    createdAt: '2026-05-16T00:00:00Z', publishedAt: '2026-05-16T00:00:00Z',
    controls: ['Type letters — keyboard or click', 'Enter — submit guess', 'Backspace — delete letter'],
  },
  {
    id: 'builtin-color-rush',
    title: 'Color Rush',
    description: 'Match your color to falling blocks. Dodge the wrong ones. Color changes randomly — stay sharp!',
    prompt: 'color matching dodge game with dynamic difficulty',
    htmlUrl: '/games/color-rush.html',
    thumbnailUrl: '/game-thumbs/builtin-color-rush.svg',
    genre: 'arcade',
    ageRating: '8+',
    status: 'published',
    authorId: 'pixelforge',
    authorName: 'PixelForge',
    playCount: 0, likeCount: 0, remixCount: 0,
    createdAt: '2026-05-16T00:00:00Z', publishedAt: '2026-05-16T00:00:00Z',
    controls: ['← → / A D — move', 'Space — change color', 'Tap left/right — move on mobile', 'Tap center — change color'],
  },
  {
    id: 'builtin-2048',
    title: '2048',
    description: 'Slide tiles, merge numbers, reach 2048! Addictive logic puzzle with high score tracking.',
    prompt: '2048 sliding tile puzzle game',
    htmlUrl: '/games/2048.html',
    thumbnailUrl: '/game-thumbs/builtin-2048.svg',
    genre: 'puzzle',
    ageRating: '8+',
    status: 'published',
    authorId: 'pixelforge',
    authorName: 'PixelForge',
    playCount: 0,likeCount: 0,remixCount: 0,
    createdAt: '2026-05-16T00:00:00Z',publishedAt: '2026-05-16T00:00:00Z',
    controls: ['Arrow keys — slide tiles', 'Swipe on mobile', 'Merge matching numbers to reach 2048'],
  },
  {
    id: 'builtin-chess',
    title: 'Chess',
    description: 'Classic chess vs AI. Choose Easy / Medium / Hard difficulty. Legal moves shown, check/checkmate detection, undo support.',
    prompt: 'chess game vs AI with minimax',
    htmlUrl: '/games/chess.html',
    thumbnailUrl: '/game-thumbs/builtin-chess.svg',
    genre: 'puzzle',
    ageRating: '8+',
    status: 'published',
    authorId: 'pixelforge',
    authorName: 'PixelForge',
    playCount: 0, likeCount: 0, remixCount: 0,
    createdAt: '2026-05-20T00:00:00Z', publishedAt: '2026-05-20T00:00:00Z',
    controls: ['Click piece to select', 'Click green dot to move', 'Undo — take back last move', 'R — new game'],
  },
  {
    id: 'builtin-flappy',
    title: 'Flappy Bird',
    description: 'Tap to flap through pipes. Simple to learn, impossible to master. How far can you go?',
    prompt: 'flappy bird pipe dodging game',
    htmlUrl: '/games/flappy.html',
    thumbnailUrl: '/game-thumbs/builtin-flappy.svg',
    genre: 'arcade',
    ageRating: '8+',
    status: 'published',
    authorId: 'pixelforge',
    authorName: 'PixelForge',
    playCount: 0, likeCount: 0, remixCount: 0,
    createdAt: '2026-05-20T00:00:00Z', publishedAt: '2026-05-20T00:00:00Z',
    controls: ['Space / Click / Tap — flap', 'Dodge the pipes', 'R — restart'],
  },
  {
    id: 'builtin-memory-match',
    title: 'Memory Match',
    description: 'Flip cards, find matching pairs. 4 difficulty levels — from 4×4 to 6×6 grids. All ages!',
    prompt: 'memory matching card flip game',
    htmlUrl: '/games/memory-match.html',
    thumbnailUrl: '/game-thumbs/builtin-memory-match.svg',
    genre: 'puzzle',
    ageRating: '8+',
    status: 'published',
    authorId: 'pixelforge',
    authorName: 'PixelForge',
    playCount: 0, likeCount: 0, remixCount: 0,
    createdAt: '2026-05-20T00:00:00Z', publishedAt: '2026-05-20T00:00:00Z',
    controls: ['Click / tap card to flip', 'Find all matching pairs', 'Fewer moves = higher score'],
  },
  {
    id: 'builtin-pong',
    title: 'Pong',
    description: 'The original arcade classic — bounce the ball past your AI opponent. First to 7 wins!',
    prompt: 'pong game vs AI opponent',
    htmlUrl: '/games/pong.html',
    thumbnailUrl: '/game-thumbs/builtin-pong.svg',
    genre: 'arcade',
    ageRating: '8+',
    status: 'published',
    authorId: 'pixelforge',
    authorName: 'PixelForge',
    playCount: 0, likeCount: 0, remixCount: 0,
    createdAt: '2026-05-20T00:00:00Z', publishedAt: '2026-05-20T00:00:00Z',
    controls: ['W / S or ↑ / ↓ — move paddle', 'Mouse — move paddle', 'Swipe on mobile'],
  },
  {
    id: 'builtin-whack-mole',
    title: 'Whack-a-Mole',
    description: 'Moles pop up — whack them fast! Speed increases every 10 seconds. How many can you whack?',
    prompt: 'whack a mole reflex game',
    htmlUrl: '/games/whack-mole.html',
    thumbnailUrl: '/game-thumbs/builtin-whack-mole.svg',
    genre: 'arcade',
    ageRating: '8+',
    status: 'published',
    authorId: 'pixelforge',
    authorName: 'PixelForge',
    playCount: 0, likeCount: 0, remixCount: 0,
    createdAt: '2026-05-20T00:00:00Z', publishedAt: '2026-05-20T00:00:00Z',
    controls: ['Click / tap the mole to whack it', 'Speed increases over time', '60 second timer'],
  },
  {
    id: 'builtin-reaction-time',
    title: 'Reaction Time',
    description: 'Wait for green — tap as fast as you can! Test your reflexes across 5 rounds. Compare your average against world benchmarks.',
    prompt: 'reaction time reflex speed test game',
    htmlUrl: '/games/reaction-time.html',
    thumbnailUrl: '/game-thumbs/builtin-reaction-time.svg',
    genre: 'arcade',
    ageRating: '8+',
    status: 'published',
    authorId: 'pixelforge',
    authorName: 'PixelForge',
    playCount: 0, likeCount: 0, remixCount: 0,
    createdAt: '2026-05-20T00:00:00Z', publishedAt: '2026-05-20T00:00:00Z',
    controls: ['Click / tap when green appears', '5 rounds — average is your score', 'Don\'t tap early!'],
  },
  {
    id: 'builtin-geography-quiz',
    title: 'Geography Quiz',
    description: 'Capitals, flags, and world facts — 10 random questions per round. How well do you know the world?',
    prompt: 'geography world capitals flags quiz game',
    htmlUrl: '/games/geography-quiz.html',
    thumbnailUrl: '/game-thumbs/builtin-geography-quiz.svg',
    genre: 'educational',
    ageRating: '8+',
    status: 'published',
    authorId: 'pixelforge',
    authorName: 'PixelForge',
    playCount: 0, likeCount: 0, remixCount: 0,
    createdAt: '2026-05-20T00:00:00Z', publishedAt: '2026-05-20T00:00:00Z',
    controls: ['Click / tap your answer', '10 questions per round', 'Hint shown for each question'],
  },
  {
    id: 'builtin-brain-math',
    title: 'Brain Math',
    description: 'Beat the timer — solve maths problems fast! Easy / Medium / Hard. Streak bonuses reward speed. 20 questions per round.',
    prompt: 'mental arithmetic brain training math game with timer',
    htmlUrl: '/games/brain-math.html',
    thumbnailUrl: '/game-thumbs/builtin-brain-math.svg',
    genre: 'educational',
    ageRating: '8+',
    status: 'published',
    authorId: 'pixelforge',
    authorName: 'PixelForge',
    playCount: 0, likeCount: 0, remixCount: 0,
    createdAt: '2026-05-20T00:00:00Z', publishedAt: '2026-05-20T00:00:00Z',
    controls: ['Click / tap the correct answer', 'Beat the timer for each question', 'Streak × 2-3 bonus on hot streaks'],
  },
]
